EPHEMERIS_DICT = {
    1: {
        1: [
            "Ano Novo",
            "Confraternização Universal",
            "Dia Mundial da Paz",
        ],
        2: ["Dia do Sanitarista"],
        3: ["Dia do Hemofílico", "Dia da Abreugrafia"],
        4: ["Dia Mundial do Braile"],
        5: ["Dia Nacional da Tipografia"],
        6: ["Dia de Reis", "Dia da Gratidão"],
        7: ["Dia do Leitor", "Dia do Mensageiro", "Dia da Liberdade de Culto"],
        8: ["Dia da Fotografia", "Dia do Fotógrafo"],
        9: ["Dia do Fico (em 1822)", "Dia do Astronauta"],
        10: ["Dia de São Gonçalo", "Dia de Peculiar People Play"],
        11: ["Dia de São Teodósio"],
        14: ["Dia do Sargento[1]"],
        19: ["Dia Oficial do Cabeleireiro"],
        20: ["Dia do Farmacêutico"],
    },
    2: {
        1: ["Dia do Publicitário"],
        2: ["Dia de Jesus Cristo", "Dia de Nossa Senhora dos Navegantes"],
        24: ["Promulgação da primeira Constituição da República do Brasil (1891)[2]"],
        25: ["Carnaval (Data Móvel)"],
        26: ["Quarta-feira de cinzas (Data Móvel)"],
    },
    3: {
        8: ["Dia Internacional da Mulher"],
        12: ["Dia do Bibliotecário"],
        14: ["Dia dos Carecas[3]"],
        15: ["Dia do Consumidor"],
        17: ["Dia de São Patrício"],
        19: ["Dia do Caráter"],
        20: ["Início do Outono"],
        27: ["Dia Mundial do Teatro", "Dia do Graffiti"],
    },
    4: {
        1: ["Dia da Mentira", "Dia da Abolição da Escravidão dos Índios - 1680"],
        2: [
            "Dia Mundial de Conscientização do Autismo",
            "Dia do Propagandista",
            "Dia Internacional do Livro Infantil",
        ],
        4: ["Dia Nacional do Parkinsoniano"],
        7: [
            "Dia do Corretor",
            "Dia do Jornalista",
            "Dia Mundial da Saúde",
            "Dia do Médico Legista",
        ],
        8: [
            "Dia Mundial de Combate ao Câncer",
            "Dia Mundial da Astronomia",
            "Dia Nacional do Sistema Braile",
        ],
        10: ["Paixão de Cristo (Data Móvel)"],
        12: ["Páscoa (Data Móvel)"],
        15: ["Dia do Desarmamento Infantil", "Dia Internacional do Ciclista"],
        18: ["Dia Nacional do Livro Infantil"],
        19: ["Dia do Índio"],
        21: [
            "Dia de Tiradentes (Inconfidência Mineira)" "Inauguração de Brasília (1960)"
        ],
        22: ["Dia do Descobrimento do Brasil (1500)"],
        23: ["Dia de São Jorge", "Dia do Escoteiro"],
        24: ["Dia de Libras (Língua Brasileira de Sinais)", "Dia Mundial do Livro"],
        28: ["Dia da Educação", "Dia da Sogra"],
        29: ["Dia Internacional da Dança"],
        30: ["Dia Nacional da Mulher"],
    },
    5: {
        1: ["Dia do Trabalhador"],
        6: ["Dia Nacional da Matemática[4]", "Dia do Cartógrafo"],
        7: ["Dia Mundial do Silêncio"],
        8: ["Dia do Artista Plástico Brasileiro"],
        10: ["Nacional do Guia de Turismo", "Dia das Mães (Data Móvel)"],
        13: [
            "Dia da Abolição da Escravatura",
            "Dia do Chefe de Cozinha",
            "Dia de Nossa Senhora de Fátima",
        ],
        15: ["Dia do Cortejo"],
        16: ["Dia dos cientistas"],
        17: [
            "Dia Internacional da Luta Contra à Homofobia.",
            "Dia Internacional da Comunicação",
        ],
        18: [
            "Dia Nacional de Combate ao Abuso e à Exploração Sexual de Crianças e Adolescentes"
        ],
        19: ["Dia do Profissional de Física"],
        22: ["Dia do Apicultor"],
        23: ["Dia do Sol"],
        24: ["Dia da Indústria Gráfica", "Dia da Lua"],
        25: ["Dia da Indústria e do Industrial"],
        27: ["Dia do Profissional Liberal"],
        28: [
            "Dia de Ação pela Saúde da Mulher",
            "Dia Mundial Contra a Mortalidade Materna",
        ],
        29: [
            "Dia do Geógrafo e do Estatístico — Instituto Brasileiro de Geografia e Estatística (IBGE)"
        ],
        31: ["Dia do Comissário de Voo"],
    },
    6: {
        5: ["Dia Mundial do meio ambiente"],
        8: ["Dia do Cunhado"],
        11: ["Dia da Marinha Brasileira[5]"],
        12: ["Dia dos Namorados[6]"],
        13: ["Dia de Santo Antônio"],
        18: ["Dia do Químico[7]"],
        19: ["Dia do Cinema Brasileiro[8]"],
        21: ["Início do Inverno (2022)"],
        23: ["Dia Olímpico[9]"],
        24: ["Dia de São João"],
        29: ["Dia de São Pedro[10][11]", "Dia de São Paulo (Santo)", "Dia do Dublador"],
    },
    7: {
        2: ["Independência da Bahia[12]"],
        8: ["Dia Nacional do Pesquisador[13]"],
        13: ["Dia Mundial do Rock"],
        15: ["Dia dos Homens"],
        20: ["Dia do Amigo"],
        26: ["Dia dos Avós"],
    },
    8: {
        9: ["Dia dos Pais (Data Móvel)"],
        11: ["Dia do Estudante"],
        13: ["Dia mundial do canhoto"],
        22: ["Dia do Folclore", "Dia do Supervisor e Coordenador"],
        23: ["Dia do Susto"],
        25: ["Dia do Soldado", "Dia do Feirante", "Dia do Miojo"],
        27: ["Dia do Psicólogo", "Dia do Corretor de Imóveis"],
        31: ["Dia do Nutricionista"],
    },
    9: {
        1: ["Dia do Profissional de Educação Física"],
        3: ["Dia Nacional do Biólogo"],
        5: ["Dia da Amazônia", "Dia dos Irmãos"],
        7: [
            "Dia da Proclamação da Independência do Brasil",
            "Dia Internacional de Conscientização sobre Distrofia Muscular de Duchenne",
        ],
        8: ["Dia de Nossa Senhora, Maria, Mãe de Jesus"],
        9: ["Dia do Administrador"],
        13: ["Dia do Programador"],
        15: ["Dia do Cliente"],
        21: ["Dia da Árvore"],
        22: ["Início da Primavera", "Dia do Contador"],
        23: ["Dia da Aurora"],
        25: ["Dia do Hipnólogo[14]", "Dia Nacional da Rádio"],
        26: ["Dia Nacional dos Surdos"],
        30: ["Dia da Secretaria"],
    },
    10: {
        1: ["Dia do Vendedor"],
        8: ["Dia do Nordestino"],
        12: [
            "Dia das Crianças",
            "Dia de Nossa Senhora Aparecida",
            "Dia do Engenheiro Agrônomo",
        ],
        15: ["Dia do Professor"],
        18: ["Dia do Médico"],
        20: ["Dia do Arquivista"],
        25: ["Dia do Dentista"],
        28: ["Dia do Servidor Público"],
        31: ["Dia da Reforma Protestante", "Dia das Bruxas (Halloween)"],
    },
    11: {
        1: ["Dia de Todos os Santos"],
        2: ["Dia de Finados"],
        7: ["Dia do Radialista"],
        12: ["Dia do Diretor de Escola"],
        14: ["Dia Nacional da Alfabetização"],
        15: ["Dia da Proclamação da República"],
        19: ["Dia da Bandeira Nacional", "Dia Internacional do Homem"],
        20: ["Dia da Consciência Negra", "Dia do Biomédico"],
        23: ["Dia do Engenheiro Eletricista"],
    },
    12: {
        4: ["Dia do Orientador Educacional", "Dia do Perito Criminal"],
        7: ["Dia Nacional da Silvicultura", "Dia Internacional da Aviação Civil"],
        8: ["Dia da Justiça"],
        9: ["Dia do Fonoaudiólogo"],
        10: ["Dia da Bíblia"],
        11: ["Dia do Engenheiro Civil"],
        18: ["Dia do Museólogo"],
        22: ["Início do Verão"],
        25: ["Natal"],
        31: ["Réveillon"],
    },
}
